### PR TITLE
Some changes to improve usability

### LINKED ISSUE #208: Missing option to pass own GitHubAPI object.
Self-hosted GitHub instances have different hostname than `github.com`.
https://github.com/JuliaWeb/GitHub.jl provides `GitHubAPI` abstract type, which is first parameter to all it's calls. 
For self-hosted instance I need to pass it everywhere, now the default instance is used.
Should I make a PR for this?

### LINKED ISSUE #222: Missing support for TeamCity
Hi, it would be great if CompatHelper would also have support for TeamCity, so it could be used in environments where Github Actions are not present.

### PR DESCRIPTION
**Pull request by racinmat**
- Added teamcity support
- Bumped GitHub version to support self-hosted github
- Passing github base url as parameter
- Removing hardcoded github.com from some places

Fixes #222 
Fixes #208

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Can you break this up into multiple smaller PRs?

**Comment by racinmat** [comment]
Ok, how many PRs and what should be their scope? 
One for github enterprise support and one for TeamCity support?

**Comment by DilumAluthge** [comment]
Let me bump some dependencies first. Then you can make those PRs. Let me think a bit about how we should break them up.

**Comment by racinmat** [comment]
Ok.

**Comment by DilumAluthge** [comment]
Can you make one PR with "passing GitHub base URL as parameter" and "removing hard coded GitHub.com"?

Once that PR is merged, you can make a second PR for teamcity.

**Comment by racinmat** [comment]
Sure, ok. I'll do new PR with the GitHub URL stuff

**Comment by DilumAluthge** [comment]
> Sure, ok. I'll do new PR with the GitHub URL stuff

Great, thanks!

**Comment by racinmat** [comment]
I just realized this PR also fixes #226. 
Should it be separate PR or can it be together with Github URL stuff?

**Comment by DilumAluthge** [comment]
I already merged the proxy and pkg server stuff separately. Take a look at master.

**Comment by DilumAluthge** [comment]
After the GitHub URL PR is merged, can you make a separate PR to fix #226?

**Pull request closed without merging**
