### PR TITLE
GitHub Enterprise support

### PR DESCRIPTION
**Pull request by tk3369**
This PR adds a new `host` parameter to the `main` function.  When it is specified, it triggers a different logic to authenticate with GitHub.  Because the API to call GitHub requires a new leading argument, I have wrapped the several GitHub functions as well.  It has been tested in my private environment.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@tk3369 Can you please bump the major version number, since this is a new feature?

**Comment by tk3369** [comment]
It's non-breaking so I bumped the minor version number instead.  Also added Compat entry for HTTP.

**Comment by DilumAluthge** [comment]
Whoops my bad, I meant to say minor. Thanks!

Can you rebase on master and squash?

**Comment by tk3369** [comment]
I only forked the project yesterday so it should be clean.  You can just squash (github button) when you merge the PR?

**Comment by DilumAluthge** [comment]
We use the Bors merge-bot, which will just do a regular merge.

And also I merged a PR earlier today that might have a merge conflict because I bumped the version number.

**Comment by tk3369** [comment]
I tried but probably messed up (not my usual workflow)... Can you check if it's ok, and if not, I'll just create a new branch.  Thanks

**Comment by DilumAluthge** [comment]
Hmmm. Maybe just make a new branch and a new PR.

**Comment by tk3369** [comment]
Replaced by PR #221

**Pull request closed without merging**
