### PR TITLE
initial attempt at subdirectory functionality

### LINKED ISSUE #138: Idea: support multiple registered Julia packages in a single GitHub repository
See also:
- https://github.com/bcbi/VersionVigilante.jl/issues/10
- https://github.com/JuliaLang/Pkg.jl/issues/1251 - "Feature request: Store multiple registered packages in a single Git repository"
- https://github.com/JuliaLang/Pkg.jl/pull/1422 - "WIP add subdir functionality"
- https://github.com/JuliaRegistries/Registrator.jl/issues/230 - "Allow registering packages in a subdir of the main repo directory"

### PR DESCRIPTION
**Pull request by SebRollen**
Initial attempt at subdirectory functionality. Not sure if I'll be able to run the integration tests from my fork, but figured I'd open this WIP PR to see

Closes #138

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Since this is a new feature, can you bump the minor version number?

**Comment by DilumAluthge** [comment]
@SebRollen I have given you the "try" permission. To run the integration tests, comment `bors try`

**Comment by DilumAluthge** [comment]
bors try

**Comment by SebRollen** [comment]
thanks! I've updated the minor version

bors try

**Comment by SebRollen** [comment]
whoops, forgot to update one reference. Not sure if I can cancel the currently running build with a new try, but here goes

bors try

**Comment by SebRollen** [comment]
bors try-

**Comment by SebRollen** [comment]
hmm, looks like the travis builds cancelled, but not sure if I did that right... One more try, and after this i'll just leave it to run haha

bors try

**Comment by DilumAluthge** [comment]
(I cancelled the Travis builds manually. Bors doesn't have the ability to cancel Travis builds.)

**Comment by SebRollen** [comment]
Ah I see, thanks for cancelling them.

So everything seemed to work for that case. However, I set up the code currently to only allow for one subdirectory, but I'm guessing that many will have the use-case where they want multiple packages per repository. Tried to fix that in https://github.com/bcbi/CompatHelper.jl/pull/195/commits/68f7936dde61be24739ef41d512c7091a961d632

bors try

**Comment by SebRollen** [comment]
Added one more commit with an updated commit message from CompatHelper about which directory in a subpackage is being updated. This is now ready for review

bors try

**Comment by SebRollen** [comment]
bors try

**Comment by DilumAluthge** [comment]
Bors try-

**Comment by DilumAluthge** [comment]
We should document this. I think for now, just a brief section to the README will suffice.

@SebRollen Can you add some content to the README documenting this feature?

**Comment by DilumAluthge** [comment]
Once we have documentation, this looks good to merge.

**Comment by SebRollen** [comment]
@DilumAluthge, added a section to the README on using subdirectories after the `Custom registries` section

**Comment by DilumAluthge** [comment]
Bors merge

**Comment by SebRollen** [comment]
Looks like a Github server error?
```julia
CompatHelper.jl integration tests: Error During Test at /home/travis/build/bcbi/CompatHelper.jl/test/runtests.jl:31
  Got exception outside of a @test
  LoadError: Error found in GitHub reponse:
  	Status Code: 502
  	Message: Server Error
  	Docs URL: 
  	Errors: 
```

**Comment by DilumAluthge** [comment]
Let's try again.

bors merge

**Pull request merged**
