### PR TITLE
Added TeamCity support

### LINKED ISSUE #222: Missing support for TeamCity
Hi, it would be great if CompatHelper would also have support for TeamCity, so it could be used in environments where Github Actions are not present.

### PR DESCRIPTION
**Pull request by racinmat**
- Added TeamCity support
- Added short section to Readme about self-hosting
- Fixes #222

### CODE REVIEW

**Comment by racinmat** [comment]
Do you think it deserves minor version, or should be just patch? @DilumAluthge

**Comment by DilumAluthge** [comment]
New feature, so bump the minor version.

**Comment by DilumAluthge** [comment]
Bors try

**Comment by DilumAluthge** [comment]
@racinmat Can you add unit tests to make sure that we have 100% code coverage of this patch?

**Comment by racinmat** [comment]
Sure.

**Comment by racinmat** [comment]
Ok, I don't know how to do that. 
I covered some parts, but I don'T know how to unit test this
```

function set_git_identity(ci_cfg::TeamCity)
    run(`git config user.name '$(ci_cfg.username)'`)
    run(`git config user.email '$(ci_cfg.email)'`)
    return nothing
end
```
I don't think it's a good idea to run such command in CI.

**Comment by racinmat** [comment]
I did my best, if you have idea how to safely cover the git command thingy, I'm all for it @DilumAluthge

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
