### PR TITLE
Update example

### PR DESCRIPTION
**Pull request by ericphanson**
Closes https://github.com/bcbi/CompatHelper.jl/issues/212

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors merge

**Comment by ericphanson** [comment]
Hold on, I had a better idea-- what about using the `path-ignore` so Version Vigilante doesn't care about stuff that tags shouldn't matter for? I pushed a commit to show what that would be

**Comment by DilumAluthge** [comment]
Can you explain the latest changes?

**Comment by DilumAluthge** [comment]
> Hold on, I had a better idea-- what about using the `path-ignore` so Version Vigilante doesn't care about stuff that tags shouldn't matter for? I pushed a commit to show what that would be

I see.

Unfortunately, Bors is not that smart, so if VersionVigilante doesn't report a status, Bors will never merge a PR.

**Comment by ericphanson** [comment]
Let me know if you want me to revert that last commit, but the idea is that you shouldn't need patch bumps for readme's because it never gets into the code, right? So version vigilante can just check changes to the code/docs files which are the ones that need a version bump.

**Comment by ericphanson** [comment]
Ah ok, I'll revert it then

**Comment by DilumAluthge** [comment]
It would be nice to figure out how to get this to work with Bors, but yeah for now it won't work.

**Comment by ericphanson** [comment]
I'm glad Bors was smart enough to cancel when I pushed after you said to merge :)

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
